CREATE TABLE LANGRAPH4J_THREAD
(
    thread_id   VARCHAR(36) PRIMARY KEY,
    thread_name VARCHAR(255),
    is_released BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE LANGRAPH4J_CHECKPOINT
(
    id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE KEY,
    checkpoint_id VARCHAR(36) PRIMARY KEY,
    thread_id     VARCHAR(36) NOT NULL,
    node_id       VARCHAR(255),
    next_node_id  VARCHAR(255),
    state_data    JSON NOT NULL,
    saved_at      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),

    CONSTRAINT LANGRAPH4J_FK_THREAD
        FOREIGN KEY (thread_id)
            REFERENCES LANGRAPH4J_THREAD (thread_id)
            ON DELETE CASCADE
);

CREATE UNIQUE INDEX IDX_LANGRAPH4J_THREAD_NAME_RELEASED
    ON LANGRAPH4J_THREAD (thread_name, is_released);